export { default as Navbar } from './Navbar'
// export { default as Sidebar } from './Sidebar/index.vue'
export { default as TagsView } from './TagsView'
export { default as AppMain } from './AppMain'
export { default as MapMain } from './MapMain'
export { default as MapNavbar } from './MapNavbar'
export { default as core } from './Core/shippingModule'
export { default as Main } from './Main'
// export { default as MapSidebar } from './MapSidebar/index.vue'
